GET http://localhost:8080/api/room/
Accept: application/json

###

GET http://localhost:8080/api/room/1
Accept: application/json

###

POST http://localhost:8080/api/room/
Content-Type: application/json

{
  "name": "10F",
  "color": "#991122"
}

###
